-- Cole isto no Supabase: SQL Editor → Run
-- Deixa o banco pronto para o sistema e para o Render.

alter table if exists vagas
  alter column origem_linha type bigint;

alter table if exists vagas
  alter column data drop not null;

alter table if exists vagas add column if not exists turma text;
alter table if exists vagas add column if not exists n_alunos integer;
alter table if exists vagas add column if not exists n_presentes integer;
alter table if exists vagas add column if not exists alocacao text;
alter table if exists vagas add column if not exists finalizado_em text;
alter table if exists vagas add column if not exists prova_recebida_em text;
alter table if exists vagas add column if not exists n_extras integer default 0;

alter table if exists viagens add column if not exists dias_aplicacao text;

alter table if exists aplicadores add column if not exists cpf text;
alter table if exists aplicadores add column if not exists numero integer;
alter table if exists aplicadores add column if not exists acesso_token text;
alter table if exists aplicadores add column if not exists tipo text default 'APLICADOR';
alter table if exists aplicadores add column if not exists matricula text;

create table if not exists diaria_valores (
    municipio_id bigint primary key references municipios(id) on delete cascade,
    valor text not null
);

create table if not exists diaria_ajustes (
    id bigint generated by default as identity primary key,
    aplicador_id bigint not null references aplicadores(id) on delete cascade,
    municipio_id bigint not null references municipios(id) on delete cascade,
    os text,
    qtd_diarias text,
    excluido integer not null default 0,
    unique (aplicador_id, municipio_id)
);

create table if not exists alunos_especiais (
    id bigint generated by default as identity primary key,
    escola_id bigint not null references escolas(id) on delete cascade,
    turma text not null,
    serie text not null,
    codigo_estudante text,
    nome text not null,
    necessidade text,
    recurso text,
    faz_com_turma text,
    sala_extra text,
    profissional_escola text,
    precisa_extra integer not null default 1
);
create index if not exists idx_alunos_escola_turma on alunos_especiais(escola_id, turma);

create table if not exists vaga_extras (
    id bigint generated by default as identity primary key,
    vaga_id bigint not null references vagas(id) on delete cascade,
    aplicador_id bigint not null references aplicadores(id) on delete cascade,
    aluno_id bigint,
    unique (vaga_id, aplicador_id, aluno_id)
);
alter table if exists vaga_extras add column if not exists aluno_id bigint;
alter table if exists vaga_extras drop constraint if exists vaga_extras_vaga_id_aplicador_id_key;
create unique index if not exists idx_vaga_extras_vaga_apl_aluno on vaga_extras(vaga_id, aplicador_id, aluno_id);
create index if not exists idx_vaga_extras_vaga on vaga_extras(vaga_id);
create index if not exists idx_vaga_extras_aplicador on vaga_extras(aplicador_id);

create index if not exists idx_vagas_escola on vagas(escola_id);
create index if not exists idx_vagas_aplicador_data on vagas(aplicador_id, data, turno);
