from __future__ import annotations

import re
import sqlite3
import threading
import time
from contextlib import contextmanager
from decimal import Decimal
from typing import Any, Iterator

from .config import DATABASE_URL, DB_PATH, USAR_POSTGRES, usando_nuvem, usando_supabase

SCHEMA_VERSION = "2"

SQLITE_SCHEMA = """
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS municipios (
    id INTEGER PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS escolas (
    id INTEGER PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    nome TEXT NOT NULL,
    municipio_id INTEGER NOT NULL REFERENCES municipios(id),
    rede TEXT NOT NULL,
    rural INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS aplicadores (
    id INTEGER PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    nome TEXT,
    cpf TEXT,
    numero INTEGER,
    acesso_token TEXT,
    tipo TEXT NOT NULL DEFAULT 'APLICADOR',
    matricula TEXT,
    ativo INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS viagens (
    id INTEGER PRIMARY KEY,
    municipio_id INTEGER NOT NULL UNIQUE REFERENCES municipios(id),
    data_saida TEXT,
    data_retorno TEXT,
    dias_aplicacao TEXT
);

CREATE TABLE IF NOT EXISTS vagas (
    id INTEGER PRIMARY KEY,
    escola_id INTEGER NOT NULL REFERENCES escolas(id),
    serie TEXT NOT NULL,
    turno TEXT NOT NULL,
    data TEXT,
    ordem INTEGER NOT NULL DEFAULT 1,
    origem_linha INTEGER UNIQUE,
    aplicador_id INTEGER REFERENCES aplicadores(id),
    status TEXT NOT NULL DEFAULT 'PREVISTA',
    finalizado_em TEXT,
    prova_recebida_em TEXT
);

CREATE INDEX IF NOT EXISTS idx_vagas_data ON vagas(data);
CREATE INDEX IF NOT EXISTS idx_vagas_aplicador ON vagas(aplicador_id);
CREATE INDEX IF NOT EXISTS idx_vagas_escola ON vagas(escola_id);
CREATE INDEX IF NOT EXISTS idx_vagas_aplicador_data ON vagas(aplicador_id, data, turno);
CREATE INDEX IF NOT EXISTS idx_escolas_municipio ON escolas(municipio_id);

CREATE TABLE IF NOT EXISTS vaga_extras (
    id INTEGER PRIMARY KEY,
    vaga_id INTEGER NOT NULL REFERENCES vagas(id) ON DELETE CASCADE,
    aplicador_id INTEGER NOT NULL REFERENCES aplicadores(id) ON DELETE CASCADE,
    UNIQUE (vaga_id, aplicador_id)
);

CREATE TABLE IF NOT EXISTS sessoes_acesso (
    token TEXT PRIMARY KEY,
    aplicador_id INTEGER NOT NULL REFERENCES aplicadores(id),
    criado_em TEXT NOT NULL,
    expira_em TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS meta (
    chave TEXT PRIMARY KEY,
    valor TEXT
);

CREATE TABLE IF NOT EXISTS diaria_valores (
    municipio_id INTEGER PRIMARY KEY REFERENCES municipios(id) ON DELETE CASCADE,
    valor TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS diaria_ajustes (
    id INTEGER PRIMARY KEY,
    aplicador_id INTEGER NOT NULL REFERENCES aplicadores(id) ON DELETE CASCADE,
    municipio_id INTEGER NOT NULL REFERENCES municipios(id) ON DELETE CASCADE,
    os TEXT,
    qtd_diarias TEXT,
    excluido INTEGER NOT NULL DEFAULT 0,
    UNIQUE (aplicador_id, municipio_id)
);
"""

PG_SCHEMA = """
CREATE TABLE IF NOT EXISTS municipios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS escolas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    nome TEXT NOT NULL,
    municipio_id BIGINT NOT NULL REFERENCES municipios(id),
    rede TEXT NOT NULL,
    rural INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS aplicadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    nome TEXT,
    cpf TEXT,
    numero INTEGER,
    acesso_token TEXT,
    tipo TEXT NOT NULL DEFAULT 'APLICADOR',
    matricula TEXT,
    ativo INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS viagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id BIGINT NOT NULL UNIQUE REFERENCES municipios(id),
    data_saida TEXT,
    data_retorno TEXT,
    dias_aplicacao TEXT
);

CREATE TABLE IF NOT EXISTS vagas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    escola_id BIGINT NOT NULL REFERENCES escolas(id),
    serie TEXT NOT NULL,
    turno TEXT NOT NULL,
    data TEXT,
    ordem INTEGER NOT NULL DEFAULT 1,
    origem_linha BIGINT UNIQUE,
    aplicador_id BIGINT REFERENCES aplicadores(id),
    status TEXT NOT NULL DEFAULT 'PREVISTA',
    finalizado_em TEXT,
    turma TEXT,
    n_alunos INTEGER,
    n_presentes INTEGER,
    alocacao TEXT,
    prova_recebida_em TEXT,
    n_extras INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_vagas_data ON vagas(data);
CREATE INDEX IF NOT EXISTS idx_vagas_aplicador ON vagas(aplicador_id);
CREATE INDEX IF NOT EXISTS idx_vagas_escola ON vagas(escola_id);
CREATE INDEX IF NOT EXISTS idx_vagas_aplicador_data ON vagas(aplicador_id, data, turno);
CREATE INDEX IF NOT EXISTS idx_escolas_municipio ON escolas(municipio_id);

CREATE TABLE IF NOT EXISTS vaga_extras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaga_id BIGINT NOT NULL REFERENCES vagas(id) ON DELETE CASCADE,
    aplicador_id BIGINT NOT NULL REFERENCES aplicadores(id) ON DELETE CASCADE,
    UNIQUE (vaga_id, aplicador_id)
);
CREATE INDEX IF NOT EXISTS idx_vaga_extras_vaga ON vaga_extras(vaga_id);
CREATE INDEX IF NOT EXISTS idx_vaga_extras_aplicador ON vaga_extras(aplicador_id);

CREATE TABLE IF NOT EXISTS sessoes_acesso (
    token TEXT PRIMARY KEY,
    aplicador_id BIGINT NOT NULL REFERENCES aplicadores(id),
    criado_em TEXT NOT NULL,
    expira_em TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS meta (
    chave TEXT PRIMARY KEY,
    valor TEXT
);

CREATE TABLE IF NOT EXISTS diaria_valores (
    municipio_id BIGINT PRIMARY KEY REFERENCES municipios(id) ON DELETE CASCADE,
    valor TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS diaria_ajustes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aplicador_id BIGINT NOT NULL REFERENCES aplicadores(id) ON DELETE CASCADE,
    municipio_id BIGINT NOT NULL REFERENCES municipios(id) ON DELETE CASCADE,
    os TEXT,
    qtd_diarias TEXT,
    excluido INTEGER NOT NULL DEFAULT 0,
    UNIQUE (aplicador_id, municipio_id)
);
"""

_TABELAS_COM_ID = {"municipios", "escolas", "aplicadores", "viagens", "vagas", "vaga_extras", "diaria_ajustes"}
_CONFLITO = {
    "municipios": "nome",
    "escolas": "codigo",
    "aplicadores": "codigo",
    "viagens": "municipio_id",
    "vagas": "origem_linha",
    "meta": "chave",
}


class Row(dict):
    """Linha que aceita row['col'], row[0] e dict(row), como o sqlite3.Row."""

    def __getitem__(self, key):
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


class PgCursor:
    def __init__(self, inner):
        self._inner = inner
        self._rows: list[Row] = []
        self._i = 0
        self.lastrowid = None

    def execute(self, sql: str, params=()):
        raw = sql.strip()
        if raw.upper().startswith("PRAGMA"):
            return self._pragma(raw)
        sql_pg = _adaptar_sql(raw)
        args = None if params is None or params == () else tuple(params)
        self._inner.execute(sql_pg, args)
        self.lastrowid = None
        self._i = 0
        if self._inner.description:
            names = [d.name for d in self._inner.description]
            fetched = self._inner.fetchall()
            self._rows = [Row({k: _valor_pg(v) for k, v in zip(names, rec)}) for rec in fetched]
            if self._rows and "id" in self._rows[0]:
                self.lastrowid = self._rows[0]["id"]
        else:
            self._rows = []
        return self

    def _pragma(self, sql: str):
        self.lastrowid = None
        self._i = 0
        self._rows = []
        m = re.match(r"PRAGMA\s+table_info\(\s*[\"']?(\w+)[\"']?\s*\)", sql, re.I)
        if not m:
            return self
        tabela = m.group(1).lower()
        self._inner.execute(
            """SELECT column_name FROM information_schema.columns
               WHERE table_schema = 'public' AND table_name = %s
               ORDER BY ordinal_position""",
            (tabela,),
        )
        self._rows = [_PragmaRow(i, r[0]) for i, r in enumerate(self._inner.fetchall())]
        return self

    def fetchone(self):
        if self._i >= len(self._rows):
            return None
        row = self._rows[self._i]
        self._i += 1
        return row

    def fetchall(self):
        rest = self._rows[self._i :]
        self._i = len(self._rows)
        return rest

    def __iter__(self):
        return iter(self.fetchall())


class _PragmaRow:
    def __init__(self, cid: int, name: str):
        self._vals = (cid, name)

    def __getitem__(self, key):
        if key in (0, "cid"):
            return self._vals[0]
        if key in (1, "name"):
            return self._vals[1]
        raise KeyError(key)

    def keys(self):
        return ("cid", "name")


class PgConnection:
    def __init__(self, inner):
        self._inner = inner
        self._cursor = None

    def execute(self, sql: str, params=()):
        if self._cursor is None:
            self._cursor = self._inner.cursor()
        return PgCursor(self._cursor).execute(sql, params)

    def executescript(self, script: str) -> None:
        for stmt in _partir_sql(script):
            if stmt.upper().startswith("PRAGMA"):
                continue
            self.execute(stmt)

    def commit(self) -> None:
        self._inner.commit()

    def rollback(self) -> None:
        self._inner.rollback()

    def close(self) -> None:
        try:
            self._inner.close()
        except Exception:
            pass
        self._cursor = None

    @property
    def closed(self) -> bool:
        try:
            return bool(self._inner.closed)
        except Exception:
            return True


def _valor_pg(valor):
    if isinstance(valor, Decimal):
        return int(valor) if valor % 1 == 0 else float(valor)
    return valor


def _partir_sql(script: str) -> list[str]:
    partes = []
    for raw in script.split(";"):
        stmt = raw.strip()
        if stmt:
            partes.append(stmt)
    return partes


def _adaptar_sql(sql: str) -> str:
    sql = sql.strip().rstrip(";")
    m_ignore = re.match(r"INSERT\s+OR\s+IGNORE\s+INTO\s+(\w+)", sql, re.I)
    m_replace = re.match(r"INSERT\s+OR\s+REPLACE\s+INTO\s+(\w+)", sql, re.I)
    if m_ignore:
        tabela = m_ignore.group(1).lower()
        sql = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", sql, count=1, flags=re.I)
        col = _CONFLITO.get(tabela)
        if col and "ON CONFLICT" not in sql.upper():
            sql += f" ON CONFLICT ({col}) DO NOTHING"
    elif m_replace:
        tabela = m_replace.group(1).lower()
        sql = re.sub(r"INSERT\s+OR\s+REPLACE\s+INTO", "INSERT INTO", sql, count=1, flags=re.I)
        col = _CONFLITO.get(tabela, "chave")
        cols = _colunas_insert(sql)
        sets = ", ".join(f"{c}=EXCLUDED.{c}" for c in cols if c.lower() != col.lower())
        if "ON CONFLICT" not in sql.upper():
            sql += f" ON CONFLICT ({col}) DO UPDATE SET {sets or f'{col}=EXCLUDED.{col}'}"
    sql = re.sub(r"ON CONFLICT\s*\(", "ON CONFLICT (", sql, flags=re.I)
    sql = _trocar_placeholders(sql)
    if _precisa_returning(sql):
        sql += " RETURNING id"
    return sql


def _colunas_insert(sql: str) -> list[str]:
    m = re.search(r"INSERT\s+INTO\s+\w+\s*\(([^)]+)\)", sql, re.I)
    if not m:
        return []
    return [c.strip() for c in m.group(1).split(",") if c.strip()]


def _precisa_returning(sql: str) -> bool:
    upper = sql.upper()
    if not upper.startswith("INSERT") or "RETURNING" in upper:
        return False
    m = re.search(r"INSERT\s+INTO\s+(\w+)", sql, re.I)
    if not m:
        return False
    return m.group(1).lower() in _TABELAS_COM_ID


def _trocar_placeholders(sql: str) -> str:
    out = []
    i = 0
    while i < len(sql):
        ch = sql[i]
        if ch == "?":
            out.append("%s")
        elif ch == "%":
            out.append("%%")
        else:
            out.append(ch)
        i += 1
    return "".join(out)


def _url_postgres(url: str) -> str:
    from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse

    if url.startswith("postgres://"):
        url = "postgresql://" + url[len("postgres://") :]
    parsed = urlparse(url)
    permitidos = {
        "sslmode",
        "connect_timeout",
        "options",
        "keepalives",
        "keepalives_idle",
        "keepalives_interval",
        "keepalives_count",
    }
    query = {k: v for k, v in parse_qsl(parsed.query) if k.lower() in permitidos}
    chaves = {k.lower() for k in query}
    if "sslmode" not in chaves:
        query["sslmode"] = "require"
    if "keepalives" not in chaves:
        query["keepalives"] = "1"
    if "keepalives_idle" not in chaves:
        query["keepalives_idle"] = "30"
    limpa = parsed._replace(query=urlencode(query))
    return urlunparse(limpa)


_pg_lock = threading.Lock()
_pg_pool: list[PgConnection] = []
_PG_POOL_MAX = 5
_pg_host_logged = False


def connect():
    if USAR_POSTGRES and DATABASE_URL:
        import psycopg
        from urllib.parse import urlparse

        global _pg_host_logged
        url = _url_postgres(DATABASE_URL)
        parsed = urlparse(url)
        if not _pg_host_logged:
            print("Postgres host:", parsed.hostname, "porta:", parsed.port)
            _pg_host_logged = True
        try:
            inner = psycopg.connect(
                url,
                autocommit=False,
                prepare_threshold=None,
                connect_timeout=15,
            )
        except Exception as exc:
            msg = str(exc).replace(parsed.password or "", "***") if parsed.password else str(exc)
            raise RuntimeError(
                "Não foi possível conectar ao Supabase. "
                f"Host {parsed.hostname} porta {parsed.port}. {msg}"
            ) from exc
        return PgConnection(inner)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def _pg_viva(conn: PgConnection) -> bool:
    try:
        if conn.closed:
            return False
        idade = time.monotonic() - getattr(conn, "_usado_em", 0)
        if idade < 45:
            return True
        conn.execute("SELECT 1")
        conn._usado_em = time.monotonic()
        return True
    except Exception:
        try:
            conn.close()
        except Exception:
            pass
        return False


def _pegar_pg() -> PgConnection:
    while True:
        cand = None
        with _pg_lock:
            if _pg_pool:
                cand = _pg_pool.pop()
        if cand is None:
            conn = connect()
            conn._usado_em = time.monotonic()
            return conn
        if _pg_viva(cand):
            cand._usado_em = time.monotonic()
            return cand


def _devolver_pg(conn: PgConnection) -> None:
    if conn.closed:
        return
    with _pg_lock:
        if len(_pg_pool) < _PG_POOL_MAX:
            _pg_pool.append(conn)
            return
    conn.close()


@contextmanager
def get_db() -> Iterator[Any]:
    if not (USAR_POSTGRES and DATABASE_URL):
        conn = connect()
        try:
            yield conn
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()
        return

    conn = _pegar_pg()
    try:
        yield conn
        conn.commit()
    except Exception:
        try:
            conn.rollback()
        except Exception:
            pass
        try:
            conn.close()
        except Exception:
            pass
        raise
    else:
        _devolver_pg(conn)


def _permitir_vaga_sem_data(conn) -> None:
    try:
        info = list(conn.execute("PRAGMA table_info(vagas)"))
    except Exception:
        return
    if not info:
        return
    data_col = next((r for r in info if r[1] == "data"), None)
    if data_col is not None and not data_col[3]:
        return
    existentes = [r[1] for r in info]
    destino = [
        "id",
        "escola_id",
        "serie",
        "turno",
        "data",
        "ordem",
        "origem_linha",
        "aplicador_id",
        "status",
        "finalizado_em",
        "turma",
        "n_alunos",
        "n_presentes",
        "alocacao",
        "prova_recebida_em",
    ]
    comuns = [c for c in destino if c in existentes]
    conn.execute("PRAGMA foreign_keys = OFF")
    conn.execute(
        """CREATE TABLE vagas_data_opcional (
            id INTEGER PRIMARY KEY,
            escola_id INTEGER NOT NULL REFERENCES escolas(id),
            serie TEXT NOT NULL,
            turno TEXT NOT NULL,
            data TEXT,
            ordem INTEGER NOT NULL DEFAULT 1,
            origem_linha INTEGER UNIQUE,
            aplicador_id INTEGER REFERENCES aplicadores(id),
            status TEXT NOT NULL DEFAULT 'PREVISTA',
            finalizado_em TEXT,
            turma TEXT,
            n_alunos INTEGER,
            n_presentes INTEGER,
            alocacao TEXT,
            prova_recebida_em TEXT
        )"""
    )
    conn.execute(
        f"INSERT INTO vagas_data_opcional ({', '.join(comuns)}) SELECT {', '.join(comuns)} FROM vagas"
    )
    conn.execute("DROP TABLE vagas")
    conn.execute("ALTER TABLE vagas_data_opcional RENAME TO vagas")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_vagas_data ON vagas(data)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_vagas_aplicador ON vagas(aplicador_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_vagas_escola ON vagas(escola_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_vagas_aplicador_data ON vagas(aplicador_id, data, turno)")
    conn.execute("PRAGMA foreign_keys = ON")


def _limpar_datas_inventadas(conn) -> None:
    ja = conn.execute(
        "SELECT valor FROM meta WHERE chave = 'limpar_datas_padrao_homologacao'"
    ).fetchone()
    if ja:
        return
    conn.execute(
        "UPDATE vagas SET data = NULL WHERE data IN ('2026-11-10', '2026-11-11')"
    )
    conn.execute(
        "INSERT OR REPLACE INTO meta(chave, valor) VALUES ('limpar_datas_padrao_homologacao', '1')"
    )


def _ensure_colunas_postgres(conn) -> None:
    stmts = [
        "ALTER TABLE aplicadores ADD COLUMN IF NOT EXISTS cpf TEXT",
        "ALTER TABLE aplicadores ADD COLUMN IF NOT EXISTS numero INTEGER",
        "ALTER TABLE aplicadores ADD COLUMN IF NOT EXISTS acesso_token TEXT",
        "ALTER TABLE aplicadores ADD COLUMN IF NOT EXISTS tipo TEXT DEFAULT 'APLICADOR'",
        "ALTER TABLE aplicadores ADD COLUMN IF NOT EXISTS matricula TEXT",
        "ALTER TABLE vagas ADD COLUMN IF NOT EXISTS finalizado_em TEXT",
        "ALTER TABLE vagas ADD COLUMN IF NOT EXISTS turma TEXT",
        "ALTER TABLE vagas ADD COLUMN IF NOT EXISTS n_alunos INTEGER",
        "ALTER TABLE vagas ADD COLUMN IF NOT EXISTS n_presentes INTEGER",
        "ALTER TABLE vagas ADD COLUMN IF NOT EXISTS alocacao TEXT",
        "ALTER TABLE vagas ADD COLUMN IF NOT EXISTS prova_recebida_em TEXT",
        "ALTER TABLE vagas ADD COLUMN IF NOT EXISTS n_extras INTEGER DEFAULT 0",
        "ALTER TABLE viagens ADD COLUMN IF NOT EXISTS dias_aplicacao TEXT",
        "ALTER TABLE vagas ALTER COLUMN origem_linha TYPE BIGINT",
        "CREATE INDEX IF NOT EXISTS idx_vagas_escola ON vagas(escola_id)",
        "CREATE INDEX IF NOT EXISTS idx_vagas_aplicador_data ON vagas(aplicador_id, data, turno)",
        """CREATE TABLE IF NOT EXISTS vaga_extras (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            vaga_id BIGINT NOT NULL REFERENCES vagas(id) ON DELETE CASCADE,
            aplicador_id BIGINT NOT NULL REFERENCES aplicadores(id) ON DELETE CASCADE,
            UNIQUE (vaga_id, aplicador_id)
        )""",
        "CREATE INDEX IF NOT EXISTS idx_vaga_extras_vaga ON vaga_extras(vaga_id)",
        "CREATE INDEX IF NOT EXISTS idx_vaga_extras_aplicador ON vaga_extras(aplicador_id)",
        """CREATE TABLE IF NOT EXISTS diaria_valores (
            municipio_id BIGINT PRIMARY KEY REFERENCES municipios(id) ON DELETE CASCADE,
            valor TEXT NOT NULL
        )""",
        """CREATE TABLE IF NOT EXISTS diaria_ajustes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            aplicador_id BIGINT NOT NULL REFERENCES aplicadores(id) ON DELETE CASCADE,
            municipio_id BIGINT NOT NULL REFERENCES municipios(id) ON DELETE CASCADE,
            os TEXT,
            qtd_diarias TEXT,
            excluido INTEGER NOT NULL DEFAULT 0,
            UNIQUE (aplicador_id, municipio_id)
        )""",
    ]
    for sql in stmts:
        try:
            conn.execute(sql)
        except Exception:
            pass
    sincronizar_sequencias(conn)


def sincronizar_sequencias(conn) -> None:
    if not (USAR_POSTGRES and DATABASE_URL):
        return
    for tabela in _TABELAS_COM_ID:
        try:
            _ajustar_sequencia(conn, tabela)
        except Exception as exc:
            print(f"Aviso: sequência {tabela}:", exc)


def ensure_colunas(conn) -> None:
    if USAR_POSTGRES and DATABASE_URL:
        _ensure_colunas_postgres(conn)
        return
    cols = {row[1] for row in conn.execute("PRAGMA table_info(aplicadores)")}
    if "cpf" not in cols:
        conn.execute("ALTER TABLE aplicadores ADD COLUMN cpf TEXT")
    if "numero" not in cols:
        conn.execute("ALTER TABLE aplicadores ADD COLUMN numero INTEGER")
    if "acesso_token" not in cols:
        conn.execute("ALTER TABLE aplicadores ADD COLUMN acesso_token TEXT")
    cols = {row[1] for row in conn.execute("PRAGMA table_info(aplicadores)")}
    if "tipo" not in cols:
        conn.execute("ALTER TABLE aplicadores ADD COLUMN tipo TEXT DEFAULT 'APLICADOR'")
        conn.execute("UPDATE aplicadores SET tipo = 'APLICADOR' WHERE tipo IS NULL")
    cols = {row[1] for row in conn.execute("PRAGMA table_info(aplicadores)")}
    if "matricula" not in cols:
        conn.execute("ALTER TABLE aplicadores ADD COLUMN matricula TEXT")
    conn.execute(
        """CREATE TABLE IF NOT EXISTS sessoes_acesso (
            token TEXT PRIMARY KEY,
            aplicador_id INTEGER NOT NULL REFERENCES aplicadores(id),
            criado_em TEXT NOT NULL,
            expira_em TEXT NOT NULL
        )"""
    )
    for row in conn.execute("SELECT id, codigo, numero FROM aplicadores"):
        codigo = row["codigo"] or ""
        m = re.search(r"(\d+)", codigo)
        if not m:
            continue
        n = int(m.group(1))
        if row["numero"] != n:
            conn.execute("UPDATE aplicadores SET numero = ? WHERE id = ?", (n, row["id"]))
    vcols = {row[1] for row in conn.execute("PRAGMA table_info(vagas)")}
    if "finalizado_em" not in vcols:
        conn.execute("ALTER TABLE vagas ADD COLUMN finalizado_em TEXT")
    if "turma" not in vcols:
        conn.execute("ALTER TABLE vagas ADD COLUMN turma TEXT")
    if "n_alunos" not in vcols:
        conn.execute("ALTER TABLE vagas ADD COLUMN n_alunos INTEGER")
    if "n_presentes" not in vcols:
        conn.execute("ALTER TABLE vagas ADD COLUMN n_presentes INTEGER")
    if not USAR_POSTGRES:
        _permitir_vaga_sem_data(conn)
    vcols = {row[1] for row in conn.execute("PRAGMA table_info(vagas)")}
    if "alocacao" not in vcols:
        conn.execute("ALTER TABLE vagas ADD COLUMN alocacao TEXT")
    vcols = {row[1] for row in conn.execute("PRAGMA table_info(vagas)")}
    if "prova_recebida_em" not in vcols:
        conn.execute("ALTER TABLE vagas ADD COLUMN prova_recebida_em TEXT")
    vcols = {row[1] for row in conn.execute("PRAGMA table_info(vagas)")}
    if "n_extras" not in vcols:
        conn.execute("ALTER TABLE vagas ADD COLUMN n_extras INTEGER NOT NULL DEFAULT 0")
    conn.execute(
        """CREATE TABLE IF NOT EXISTS vaga_extras (
            id INTEGER PRIMARY KEY,
            vaga_id INTEGER NOT NULL REFERENCES vagas(id) ON DELETE CASCADE,
            aplicador_id INTEGER NOT NULL REFERENCES aplicadores(id) ON DELETE CASCADE,
            UNIQUE (vaga_id, aplicador_id)
        )"""
    )
    conn.execute("CREATE INDEX IF NOT EXISTS idx_vaga_extras_vaga ON vaga_extras(vaga_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_vaga_extras_aplicador ON vaga_extras(aplicador_id)")
    try:
        vicols = {row[1] for row in conn.execute("PRAGMA table_info(viagens)")}
        if "dias_aplicacao" not in vicols:
            conn.execute("ALTER TABLE viagens ADD COLUMN dias_aplicacao TEXT")
    except Exception:
        pass
    conn.execute("CREATE INDEX IF NOT EXISTS idx_vagas_escola ON vagas(escola_id)")
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_vagas_aplicador_data ON vagas(aplicador_id, data, turno)"
    )
    conn.execute(
        """CREATE TABLE IF NOT EXISTS diaria_valores (
            municipio_id INTEGER PRIMARY KEY REFERENCES municipios(id) ON DELETE CASCADE,
            valor TEXT NOT NULL
        )"""
    )
    conn.execute(
        """CREATE TABLE IF NOT EXISTS diaria_ajustes (
            id INTEGER PRIMARY KEY,
            aplicador_id INTEGER NOT NULL REFERENCES aplicadores(id) ON DELETE CASCADE,
            municipio_id INTEGER NOT NULL REFERENCES municipios(id) ON DELETE CASCADE,
            os TEXT,
            qtd_diarias TEXT,
            excluido INTEGER NOT NULL DEFAULT 0,
            UNIQUE (aplicador_id, municipio_id)
        )"""
    )


def init_db() -> None:
    with get_db() as conn:
        if USAR_POSTGRES and DATABASE_URL:
            conn.executescript(PG_SCHEMA)
            conn.execute(
                "INSERT OR REPLACE INTO meta(chave, valor) VALUES (?, ?)",
                ("schema", SCHEMA_VERSION),
            )
            ensure_colunas(conn)
        else:
            conn.execute(
                "CREATE TABLE IF NOT EXISTS meta (chave TEXT PRIMARY KEY, valor TEXT)"
            )
            conn.executescript(SQLITE_SCHEMA)
            conn.execute(
                "INSERT OR REPLACE INTO meta(chave, valor) VALUES (?, ?)",
                ("schema", SCHEMA_VERSION),
            )
            ensure_colunas(conn)
    if USAR_POSTGRES and DATABASE_URL:
        _migrar_sqlite_se_postgres_vazio()
    elif usando_nuvem():
        try:
            _migrar_sqlite_se_nuvem_vazia()
        except Exception as exc:
            print("Aviso: ainda não gravou no Supabase.", exc)
    with get_db() as conn:
        _limpar_datas_inventadas(conn)


def _migrar_sqlite_se_nuvem_vazia() -> None:
    from .nuvem import contar_municipios_nuvem, enviar_do_sqlite, erro_nuvem, puxar_para_sqlite

    try:
        n_nuvem = contar_municipios_nuvem()
    except Exception as exc:
        raise erro_nuvem(exc) from exc
    conn = connect()
    try:
        n_local = conn.execute("SELECT COUNT(*) n FROM municipios").fetchone()["n"]
        n_vagas = conn.execute("SELECT COUNT(*) n FROM vagas").fetchone()["n"]
        if n_nuvem == 0 and n_local:
            enviar_do_sqlite(conn)
        elif n_nuvem and not n_local and not n_vagas:
            puxar_para_sqlite(conn)
    except Exception as exc:
        raise erro_nuvem(exc) from exc
    finally:
        conn.close()


def _tabelas_sqlite(src: sqlite3.Connection) -> set[str]:
    return {
        r[0]
        for r in src.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        )
    }


def _colunas_sqlite(src: sqlite3.Connection, tabela: str) -> list[str]:
    return [row[1] for row in src.execute(f"PRAGMA table_info({tabela})")]


def _copiar_tabela(src: sqlite3.Connection, dest, tabela: str, colunas: list[str]) -> None:
    existentes = _colunas_sqlite(src, tabela)
    usar = [c for c in colunas if c in existentes]
    if not usar:
        return
    rows = src.execute(f"SELECT {', '.join(usar)} FROM {tabela}").fetchall()
    if not rows:
        return
    ph = ", ".join("?" for _ in usar)
    cols = ", ".join(usar)
    for r in rows:
        dest.execute(
            f"INSERT INTO {tabela} ({cols}) VALUES ({ph})",
            tuple(r[c] for c in usar),
        )


def _ajustar_sequencia(dest, tabela: str) -> None:
    if tabela not in _TABELAS_COM_ID:
        return
    max_id = dest.execute(f"SELECT COALESCE(MAX(id), 0) n FROM {tabela}").fetchone()["n"]
    if not max_id:
        return
    dest.execute(
        "SELECT setval(pg_get_serial_sequence(?, 'id'), ?, true)",
        (tabela, int(max_id)),
    )


def _migrar_sqlite_se_postgres_vazio() -> None:
    if not DB_PATH.exists():
        return
    with get_db() as pg:
        n = pg.execute("SELECT COUNT(*) n FROM municipios").fetchone()["n"]
        if n:
            return
    src = sqlite3.connect(DB_PATH)
    src.row_factory = sqlite3.Row
    try:
        tabelas = _tabelas_sqlite(src)
        if "municipios" not in tabelas:
            return
        nsrc = src.execute("SELECT COUNT(*) FROM municipios").fetchone()[0]
        if not nsrc:
            return
        with get_db() as pg:
            _copiar_tabela(src, pg, "municipios", ["id", "nome"])
            if "escolas" in tabelas:
                _copiar_tabela(
                    src,
                    pg,
                    "escolas",
                    ["id", "codigo", "nome", "municipio_id", "rede", "rural"],
                )
            if "aplicadores" in tabelas:
                _copiar_tabela(
                    src,
                    pg,
                    "aplicadores",
                    ["id", "codigo", "nome", "cpf", "numero", "acesso_token", "ativo", "tipo", "matricula"],
                )
            if "viagens" in tabelas:
                _copiar_tabela(
                    src,
                    pg,
                    "viagens",
                    ["id", "municipio_id", "data_saida", "data_retorno", "dias_aplicacao"],
                )
            if "vagas" in tabelas:
                _copiar_tabela(
                    src,
                    pg,
                    "vagas",
                    [
                        "id",
                        "escola_id",
                        "serie",
                        "turno",
                        "data",
                        "ordem",
                        "origem_linha",
                        "aplicador_id",
                        "status",
                        "finalizado_em",
                        "turma",
                        "n_alunos",
                        "n_presentes",
                        "alocacao",
                        "prova_recebida_em",
                        "n_extras",
                    ],
                )
            if "vaga_extras" in tabelas:
                _copiar_tabela(
                    src,
                    pg,
                    "vaga_extras",
                    ["id", "vaga_id", "aplicador_id"],
                )
            if "sessoes_acesso" in tabelas:
                _copiar_tabela(
                    src,
                    pg,
                    "sessoes_acesso",
                    ["token", "aplicador_id", "criado_em", "expira_em"],
                )
            if "meta" in tabelas:
                _copiar_tabela(src, pg, "meta", ["chave", "valor"])
            if "diaria_valores" in tabelas:
                _copiar_tabela(src, pg, "diaria_valores", ["municipio_id", "valor"])
            if "diaria_ajustes" in tabelas:
                _copiar_tabela(
                    src,
                    pg,
                    "diaria_ajustes",
                    ["id", "aplicador_id", "municipio_id", "os", "qtd_diarias", "excluido"],
                )
            for tabela in ("municipios", "escolas", "aplicadores", "viagens", "vagas", "vaga_extras", "diaria_ajustes"):
                if tabela in tabelas:
                    _ajustar_sequencia(pg, tabela)
    finally:
        src.close()


def row_to_dict(row) -> dict | None:
    if row is None:
        return None
    if isinstance(row, dict):
        return dict(row)
    return {k: row[k] for k in row.keys()}


def rows_to_dicts(rows) -> list[dict]:
    return [row_to_dict(r) for r in rows]


# Compatibilidade com imports antigos
SCHEMA = SQLITE_SCHEMA
